# Generated by Django 4.2.2 on 2023-07-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
                ("category_slug", models.SlugField(unique=True)),
                ("category_createdBy", models.CharField(blank=True, max_length=50)),
                ("category_description", models.CharField(blank=True, max_length=500)),
                ("category_img", models.ImageField(upload_to="photos/categories")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                ("color_createdBy", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(max_length=10)),
                ("color_slug", models.SlugField(blank=True, max_length=30)),
                ("color_desName", models.CharField(blank=True, max_length=20)),
                ("is_available", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50, unique=True)),
                ("product_slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="photos/products")),
                ("stock", models.IntegerField()),
                ("product_createdBy", models.CharField(blank=True, max_length=50)),
                ("is_available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                ("size", models.CharField(blank=True, max_length=10)),
                ("size_slug", models.SlugField(blank=True, max_length=20)),
                ("size_createdBy", models.CharField(blank=True, max_length=50)),
                ("is_available", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="store/products")),
                ("gallery_createdBy", models.CharField(blank=True, max_length=50)),
                (
                    "color",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.color",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.size",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Gallery",
                "verbose_name_plural": "Image Gallery",
            },
        ),
        migrations.AddField(
            model_name="color",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.product"
            ),
        ),
        migrations.AddField(
            model_name="color",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.size"
            ),
        ),
    ]
