# Generated by Django 4.2.2 on 2023-07-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="category_img", new_name="category_image",
        ),
    ]
