# Generated by Django 4.2.2 on 2023-07-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_category_img_category_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
