# Generated by Django 4.2.2 on 2023-07-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_description_productaddinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productaddinfo",
            options={
                "verbose_name": "Product Additional Info",
                "verbose_name_plural": "Product Additional Info",
            },
        ),
    ]
