# Generated by Django 4.2.2 on 2023-07-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_productaddinfo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productaddinfo",
            name="brand",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
