# Generated by Django 4.2.2 on 2023-07-11 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0006_productaddinfo_brand"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("review", models.TextField(blank=True, max_length=1000)),
                ("rating", models.FloatField()),
                (
                    "image1",
                    models.ImageField(blank=True, upload_to="customer_reviews/images"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, upload_to="customer_reviews/images"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, upload_to="customer_reviews/images"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, upload_to="customer_reviews/images"),
                ),
                ("ip", models.CharField(blank=True, max_length=20)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
