# Generated by Django 4.2.2 on 2023-07-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_productaddinfo_options"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="color",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.color",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="store.size"
            ),
        ),
    ]
