# Generated by Django 4.2.2 on 2023-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartitem_color_alter_cartitem_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem", name="color", field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="cartitem", name="size", field=models.CharField(blank=True),
        ),
    ]
