# Generated by Django 4.2.2 on 2023-07-07 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax", options={"verbose_name": "TAX", "verbose_name_plural": "Taxes"},
        ),
        migrations.AddField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
