# Generated by Django 4.2.2 on 2023-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="size",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
